#!/usr/bin/env python3
"""Generate StringMap.ets from entry/src/main/resources/*/element/string.json.

Run this whenever resource string.json files change.
The generated file is used by AppStrings for runtime locale-aware string
resolution, avoiding the cold-start-only limitation of
i18n.System.setAppPreferredLanguage.
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RESOURCES = ROOT / "entry" / "src" / "main" / "resources"
OUTPUT = ROOT / "shared" / "src" / "main" / "ets" / "i18n" / "StringMap.ets"
LOCALES = ["en_US", "zh_CN", "zh_HK", "zh_TW"]


def load_locale_strings(locale: str) -> dict[str, str]:
    path = RESOURCES / locale / "element" / "string.json"
    if not path.exists():
        raise FileNotFoundError(f"Missing resource file: {path}")
    data = json.loads(path.read_text(encoding="utf-8"))
    strings = data.get("string", [])
    return {s["name"]: s["value"] for s in strings}


def main() -> None:
    locale_strings = {locale: load_locale_strings(locale) for locale in LOCALES}
    all_names = sorted(locale_strings["en_US"].keys())

    for locale in LOCALES:
        count = len(locale_strings[locale])
        if count != len(all_names):
            raise ValueError(
                f"{locale} has {count} keys, expected {len(all_names)}"
            )

    lines = [
        "// GENERATED by scripts/generate_string_map.py — do not edit manually",
        "// Provides locale-aware string resolution for AppStrings runtime lookups",
        "",
        "/**",
        " * Maps locale key (e.g. 'en_US') → resource name → value",
        " */",
        'export const STRING_MAP: Record<string, Record<string, string>> = {',
    ]

    for locale in LOCALES:
        lines.append(f"  '{locale}': {{")
        for name in all_names:
            value = locale_strings[locale].get(name, "")
            escaped = (
                value.replace("\\", "\\\\")
                .replace("'", "\\'")
                .replace("\n", "\\n")
            )
            lines.append(f"    '{name}': '{escaped}',")
        lines.append("  },")

    lines.append("};")
    lines.append("")

    lines.append("/**")
    lines.append(" * Resource references keyed by resource name.")
    lines.append(
        " * Used at init time to build an ID→name reverse map."
    )
    lines.append(
        " * Each $r() resolves to the same Resource object as AppStrings.R_* constants."
    )
    lines.append(" */")
    lines.append(
        "export const RESOURCE_BY_NAME: Record<string, Resource> = {"
    )

    for name in all_names:
        lines.append(f"  '{name}': $r('app.string.{name}'),")

    lines.append("};")

    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(
        f"Generated {OUTPUT.relative_to(ROOT)}: "
        f"{len(all_names)} keys × {len(LOCALES)} locales"
    )


if __name__ == "__main__":
    main()
