#!/usr/bin/env node
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const indexPage = readFileSync('entry/src/main/ets/pages/Index.ets', 'utf8')
const homePage = readFileSync('feature/feed/src/main/ets/pages/HomePage.ets', 'utf8')
const discoverPage = readFileSync('feature/node/src/main/ets/pages/DiscoverPage.ets', 'utf8')
const notificationPage = readFileSync('entry/src/main/ets/pages/NotificationPage.ets', 'utf8')
const accountPage = readFileSync('entry/src/main/ets/pages/AccountPage.ets', 'utf8')
const settingsPage = readFileSync('feature/settings/src/main/ets/pages/SettingsPage.ets', 'utf8')
const saveCoordinator = readFileSync('feature/settings/src/main/ets/model/SettingsSaveCoordinator.ets', 'utf8')
const bootstrap = readFileSync('shared/src/main/ets/settings/SettingsBootstrap.ets', 'utf8')
const homeTabSettings = readFileSync('shared/src/main/ets/settings/HomeTabSettings.ets', 'utf8')
const storageKeys = readFileSync('shared/src/main/ets/constants/StorageKeys.ets', 'utf8')
const sharedIndex = readFileSync('shared/src/main/ets/Index.ets', 'utf8')
const appStrings = readFileSync('shared/src/main/ets/i18n/AppStrings.ets', 'utf8')

function mustContain(text, needle, label = needle) {
  assert.notEqual(text.indexOf(needle), -1, `${label} not found`)
}

mustContain(storageKeys, "HOME_TAB_AUTO_HIDE: string = 'homeTabAutoHide'", 'home tab storage key')
mustContain(homeTabSettings, 'static readonly DEFAULT_AUTO_HIDE: boolean = true', 'default auto-hide enabled')
mustContain(homeTabSettings, 'store.getSync(KEY_AUTO_HIDE, HomeTabSettings.DEFAULT_AUTO_HIDE)', 'missing preference fallback')
mustContain(homeTabSettings, 'setAppStorageValue<boolean>(StorageKeys.HOME_TAB_AUTO_HIDE, autoHide)', 'AppStorage apply')
mustContain(sharedIndex, "export { HomeTabSettings } from './settings/HomeTabSettings'", 'shared HomeTabSettings export')
mustContain(sharedIndex, "export type { HomeTabSettingsSnapshot } from './settings/HomeTabSettings'", 'shared HomeTabSettingsSnapshot export')
mustContain(bootstrap, 'restoreHomeTabs(context, settingsStore)', 'bootstrap restore call')
mustContain(bootstrap, 'HomeTabSettings.loadFromStore(settingsStore)', 'bootstrap shared store load')
mustContain(saveCoordinator, 'static saveHomeTabAutoHide(context: common.UIAbilityContext, enabled: boolean): void', 'settings save coordinator method')

mustContain(appStrings, "R_HOME_TAB_AUTO_HIDE: Resource = $r('app.string.home_tab_auto_hide')", 'home tab label resource')
mustContain(settingsPage, '@StorageLink(StorageKeys.HOME_TAB_AUTO_HIDE) homeTabAutoHide: boolean = HomeTabSettings.DEFAULT_AUTO_HIDE', 'settings StorageLink')
mustContain(settingsPage, 'this.TogglePreferenceRow(AppStrings.R_HOME_TAB_AUTO_HIDE, this.homeTabAutoHide', 'settings toggle row')
mustContain(settingsPage, 'SettingsSaveCoordinator.saveHomeTabAutoHide(context, enabled)', 'settings save call')

mustContain(indexPage, '@StorageLink(StorageKeys.HOME_TAB_AUTO_HIDE)', 'Index StorageLink')
mustContain(indexPage, "@Watch('onHomeTabAutoHideChanged')", 'Index watch')
mustContain(indexPage, 'private homeTabScrollers: Scroller[]', 'Index owned tab scroller refs')
mustContain(indexPage, 'this.tc.bindScroller(index, this.homeTabScrollers[index])', 'HDS tab scroller binding')
mustContain(indexPage, 'this.tc.unbindScroller(this.homeTabScrollers[index])', 'disabled state unbinds HDS scrollers')
mustContain(indexPage, 'this.tc.applyShowAnimation(HdsAnimationMode.SCROLL_ANIMATION)', 'HDS scroll animation mode used to restore visible tabs')
mustContain(indexPage, 'this.tc.applyHideAnimation(HdsAnimationMode.SCROLL_ANIMATION)', 'HDS scroll animation mode used to hide tabs')
mustContain(indexPage, 'private restoreHomeTabIfHidden(): void', 'guarded tab restore helper')
mustContain(indexPage, 'if (this.homeTabVisibleByScroll) {\n      return\n    }\n    this.homeTabVisibleByScroll = true\n    this.tc.applyShowAnimation', 'show animation is guarded by hidden state')
mustContain(indexPage, 'this.tc.bindScroller(index, scroller)\n      this.restoreHomeTabIfHidden()', 'scroller switch only restores when hidden')
mustContain(indexPage, 'this.tc.bindScroller(index, this.homeTabScrollers[index])\n      }\n      this.restoreHomeTabIfHidden()', 'auto-hide enable only restores when hidden')
mustContain(indexPage, 'this.tc.unbindScroller(this.homeTabScrollers[index])\n    }\n    this.restoreHomeTabIfHidden()', 'auto-hide disable restores from hidden without unconditional show')
assert.equal(indexPage.match(/applyShowAnimation\(HdsAnimationMode\.SCROLL_ANIMATION\)/g)?.length, 2, 'show animation should only be called by guarded restore and scroll animation')
mustContain(indexPage, 'private onHomeTabDidScroll(index: number, offset: number, state: ScrollState): void', 'Index scroll-driven hide/show handler')
const handlerIndex = indexPage.indexOf('private onHomeTabDidScroll(index: number, offset: number, state: ScrollState): void')
const topFallbackIndex = indexPage.indexOf('if (offset <= this.HOME_TAB_SCROLL_DELTA_PX)', handlerIndex)
const idleGuardIndex = indexPage.indexOf('if (state === ScrollState.Idle)', handlerIndex)
const reverseDirectionIndex = indexPage.indexOf('if (isReverseScroll)', handlerIndex)
const forwardDirectionIndex = indexPage.indexOf('if (isForwardScroll)', handlerIndex)
assert.ok(indexPage.includes('const isReverseScroll = delta < -this.HOME_TAB_SCROLL_DELTA_PX'), 'reverse direction must be derived from delta')
assert.ok(indexPage.includes('const isForwardScroll = delta > this.HOME_TAB_SCROLL_DELTA_PX'), 'forward direction must be derived from delta')
assert.ok(topFallbackIndex !== -1, 'top fallback should restore when offset returns to top')
assert.ok(idleGuardIndex !== -1, 'Idle guard should remain for non-top programmatic settle events')
assert.ok(reverseDirectionIndex !== -1, 'reverse/content-up direction should restore before forward hide')
assert.ok(forwardDirectionIndex !== -1, 'forward/content-down direction should hide')
assert.ok(topFallbackIndex < idleGuardIndex, 'programmatic status-bar/top restore must run before Idle guard')
assert.ok(reverseDirectionIndex < forwardDirectionIndex, 'reverse restore must be evaluated before forward hide')
assert.equal(indexPage.indexOf('if (isForwardScroll || offset > this.HOME_TAB_SCROLL_DELTA_PX)'), -1, 'absolute non-top offset must not re-hide after reverse restore')
assert.equal(indexPage.indexOf('if (offset > this.HOME_TAB_SCROLL_DELTA_PX) {'), -1, 'absolute offset must not be a hide branch')
mustContain(indexPage, 'HomePage({', 'HomePage receives scroller callback')
mustContain(indexPage, 'scroller: this.homeTabScrollers[1]', 'Discover scroller binding')
mustContain(indexPage, 'NotificationPage({', 'Notification page constructed')
mustContain(indexPage, 'scroller: this.homeTabScrollers[2]', 'Notification scroller binding')
mustContain(indexPage, 'AccountDashboardPage({', 'Account page constructed')
mustContain(indexPage, 'scroller: this.homeTabScrollers[3]', 'Account scroller binding')

mustContain(homePage, 'private feedScrollers: Map<string, Scroller>', 'Home feed scroller registry')
mustContain(homePage, 'onScrollerReady?: (scroller: Scroller) => void', 'Home scroller callback')
mustContain(homePage, 'FeedListPage({', 'Home creates FeedListPage')
mustContain(homePage, 'scroller: this.scrollerForTab(tab.key)', 'Home per-feed scroller')
mustContain(homePage, 'this.onFeedScrollerReady(tabKey, scroller)', 'Home relays current feed scroller')
mustContain(discoverPage, 'scroller: Scroller = new Scroller()', 'Discover externally bindable scroller')
mustContain(notificationPage, 'scroller: Scroller = new Scroller()', 'Notification externally bindable scroller')
mustContain(accountPage, 'scroller: Scroller = new Scroller()', 'Account externally bindable scroller')
mustContain(accountPage, 'SecondaryListScaffold({\n        scroller: this.scroller,', 'Account passes scroller to scaffold')

for (const locale of ['base', 'en_US', 'zh_CN', 'zh_HK', 'zh_TW']) {
  const resource = JSON.parse(readFileSync(`entry/src/main/resources/${locale}/element/string.json`, 'utf8'))
  const names = new Set(resource.string.map(item => item.name))
  assert.ok(names.has('home_tab_auto_hide'), `${locale} missing home_tab_auto_hide`)
}

console.log('test_home_tab_auto_hide_static: PASS')
